
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.apalis-amqp]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.amq-protocol]]
version = "8.3.1"
criteria = "safe-to-deploy"

[[exemptions.amq-protocol-tcp]]
version = "8.3.1"
criteria = "safe-to-deploy"

[[exemptions.amq-protocol-types]]
version = "8.3.1"
criteria = "safe-to-deploy"

[[exemptions.amq-protocol-uri]]
version = "8.3.1"
criteria = "safe-to-deploy"

[[exemptions.apalis]]
version = "1.0.0-beta.2"
criteria = "safe-to-run"

[[exemptions.apalis-amqp]]
version = "1.0.0-beta.1"
criteria = "safe-to-deploy"

[[exemptions.apalis-core]]
version = "1.0.0-beta.2"
criteria = "safe-to-deploy"

[[exemptions.asn1-rs]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.asn1-rs-derive]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.asn1-rs-impl]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.async-channel]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.async-executor]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.async-global-executor]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.async-global-executor-trait]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.async-global-executor-trait]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.async-io]]
version = "2.3.3"
criteria = "safe-to-deploy"

[[exemptions.async-lock]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.async-reactor-trait]]
version = "3.1.1"
criteria = "safe-to-deploy"

[[exemptions.async-task]]
version = "4.7.1"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.81"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-rs]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.backon]]
version = "1.5.2"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.73"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bindgen]]
version = "0.72.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.blocking]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.38"
criteria = "safe-to-deploy"

[[exemptions.cexpr]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.cmake]]
version = "0.1.54"
criteria = "safe-to-deploy"

[[exemptions.cms]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cookie-factory]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.20"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.deadpool]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.deadpool-lapin]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.deadpool-runtime]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.der-parser]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.der_derive]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.11"
criteria = "safe-to-deploy"

[[exemptions.des]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.executor-trait]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.executor-trait]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.flagset]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-lite]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-rustls]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.inout]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.lapin]]
version = "3.6.0"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.155"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.22"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-bigint]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.46"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.2"
criteria = "safe-to-deploy"

[[exemptions.oid-registry]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.p12-keystore]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.piper]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pkcs12]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs5]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.polling]]
version = "3.7.2"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.36"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.rc2]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.reactor-trait]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.reactor-trait]]
version = "3.1.1"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.5"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustc-hash]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.rusticata-macros]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.34"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.32"
criteria = "safe-to-deploy"

[[exemptions.rustls-connector]]
version = "0.21.11"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.6"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.salsa20]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.scrypt]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.204"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.204"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.120"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.90"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.synstructure]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.tcp-stream]]
version = "0.30.9"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.3"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.3"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.39.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-executor-trait]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-reactor-trait]]
version = "3.9.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.16"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.43"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.35"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.7+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasip2]]
version = "1.0.1+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.x509-cert]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.x509-parser]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"
